name: Android Build
on:
  workflow_dispatch:
  push:
    paths:
      - 'vcpkg/**'
      - 'vcpkg.json'
      - 'VCPKG_BASELINE'
      - 'app/**'
      - 'core/**'
      - 'scripts/**'
      - 'cmake/**'
      - 'cmake_templates/**'
      - 'CMakeLists.txt'
      - '.github/workflows/android.yml'

  release:
    types:
      - published

concurrency:
  group: ci-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android_build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - TRIPLET: 'arm64-android'
            ANDROID_ABI: 'arm64-v8a'
            BUILD_OFFSET: 50

    runs-on: macos-26
    env:
      NDK_VERSION: 'r27' # '27.2.12479018'
      NDK_VERSION_FULL: r27c
      JDK_VERSION: 17
      SDK_PLATFORM: android-36
      VCPKG_BINARY_SOURCES: 'clear'
      SDK_BUILD_TOOLS: 36.0.0
      CMAKE_VERSION: '4.3.2'
      XC_VERSION: ${{ '26.4.1' }}
      VCPKG_ROOT: '${{ github.workspace }}/vcpkg'
      LC_ALL: 'en_US.UTF-8' #fastlane
      LANG: 'en_US.UTF-8' #fastlane

    steps:
      - uses: actions/checkout@v6
        with:
          path: mm

      #
      # Free up space by removing unused XCode versions
      #
      # See https://github.com/actions/runner-images/issues/10511
      # Removes all XCode versions, but the one we use
      #
      - name: Delete unused XC versions to reclaim disk space
        shell: bash
        run: |
          find /Applications/Xcode_* -maxdepth 0 -type d ! -name 'Xcode_${{ env.XC_VERSION }}.app' -exec rm -rf {} \;

      - name: Install Build Dependencies
        run: |
          brew uninstall cmake
          brew install gnupg
          brew install automake bison flex gnu-sed autoconf-archive libtool gettext lcov openssl mono
          echo $(brew --prefix bison)/bin >> $GITHUB_PATH
          echo $(brew --prefix flex)/bin >> $GITHUB_PATH
          echo $(brew --prefix gettext)/bin >> $GITHUB_PATH

          if  [[ ${{ github.ref }} == refs/tags/* ]]
          then
              export GIT_TAG="${GITHUB_REF//refs\/tags\//}"
              export GIT_BRANCH=""
          else
              export GIT_TAG=""
              export GIT_BRANCH="${GITHUB_REF//refs\/heads\//}"
          fi
          echo "GIT_TAG: $GIT_TAG"
          echo "GIT_BRANCH: $GIT_BRANCH"
          echo "GIT_TAG=$GIT_TAG" >> $GITHUB_ENV
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      - name: Install CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: ${{ env.CMAKE_VERSION }}

      - name: Setup XCode
        uses: maxim-lobanov/setup-xcode@v1.7.0
        with:
          xcode-version: ${{ env.XC_VERSION }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ env.TRIPLET }}
          max-size: 200M

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: ${{ env.NDK_VERSION_FULL }}
          add-to-path: true

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: zulu

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Install Android Tools
        run: |
          sdkmanager --verbose "platforms;${SDK_PLATFORM}" "build-tools;${SDK_BUILD_TOOLS}" tools platform-tools

      - name: Install vcpkg
        shell: bash
        run: |
          mkdir -p "${{ env.VCPKG_ROOT }}"
          cd "${{ env.VCPKG_ROOT }}"
          git init
          git remote add origin https://github.com/microsoft/vcpkg.git
          git pull origin master
          VCPKG_TAG=`cat ${{ github.workspace }}/mm/VCPKG_BASELINE`
          git checkout ${VCPKG_TAG}
          cd "${{ env.VCPKG_ROOT }}"
          chmod +x ./bootstrap-vcpkg.sh
          ./bootstrap-vcpkg.sh

      - name: Cache vcpkg archives
        uses: actions/cache@v4
        with:
          path: ~/.cache/vcpkg/archives
          key: vcpkg-archives-${{ matrix.TRIPLET }}-${{ hashFiles('mm/vcpkg.json', 'mm/VCPKG_BASELINE') }}
          restore-keys: |
            vcpkg-archives-${{ matrix.TRIPLET }}-

      - name: Calculate build number
        run: |
          BUILD_NUM=$GITHUB_RUN_NUMBER$((GITHUB_RUN_ATTEMPT + ${{ matrix.BUILD_OFFSET }}))
          echo "MM_VERSION_CODE=${BUILD_NUM}" >> $GITHUB_ENV

          echo "Version code: ${BUILD_NUM}"

          # add build number to summary
          echo ":rocket: Build number: ${BUILD_NUM}" >> $GITHUB_STEP_SUMMARY

      - name: Configure app
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          mkdir -p ${{ github.workspace }}/build-mm
          cd ${{ github.workspace }}/build-mm

          export PATH=${{ env.VCPKG_ROOT }}:$PATH
          export ANDROID_ABI=${{ matrix.ANDROID_ABI }}

          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DANDROID_SDK_ROOT=${ANDROID_SDK_ROOT} \
            -DVCPKG_HOST_TRIPLET=arm64-osx \
            -DVCPKG_TARGET_TRIPLET="${{ matrix.TRIPLET }}" \
            -DVCPKG_INSTALL_OPTIONS="--allow-unsupported" \
            -DANDROID_ABI=${{ matrix.ANDROID_ABI }} \
            -DQT_ANDROID_ABIS=${{ matrix.ANDROID_ABI }} \
            -DUSE_MM_SERVER_API_KEY=No \
            -DUSE_KEYCHAIN=No \
            -DCMAKE_TOOLCHAIN_FILE:PATH="${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake" \
            -GNinja \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -S ../mm \
            -B ./

      - name: Build APK
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          cd ${{ github.workspace }}/build-mm
          ninja apk

          echo "APKs:"
          find . | grep .apk

      - name: Rename APK artefact
        run: |
          APK_PATH=$(find ${{ github.workspace }}/build-mm -iname "*.apk" | head -n 1)
          echo "Found APK: $APK_PATH"
          cp "$APK_PATH" ${{ github.workspace }}/geomarkmaps-${{ env.MM_VERSION_CODE }}-${{ matrix.ANDROID_ABI }}.apk

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v6
        with:
          path: ${{ github.workspace }}/geomarkmaps-${{ env.MM_VERSION_CODE }}-${{ matrix.ANDROID_ABI }}.apk
          name: Geomark Maps ${{ env.MM_VERSION_CODE }} APK [${{ matrix.ANDROID_ABI }}]